### ISSUE TITLE
Issue with Kernel.connectTo and Comms

### ISSUE THREAD

**Issue by AlexTugarev** [jupyter/jupyter-js-services#233]
Consider the following situation:
- a session+kernel is created for a console
- a custom widget which … 
 - connects to a running kernel via `IServiceManager.kernels.connectTo`
 - connects a Comm to the second kernel client

When the kernel sends a Comm message, each time this message is processed in `Kernel. _handleCommMsg` ([L874](https://github.com/jupyter/jupyter-js-services/blob/master/src/kernel/default.ts#L874)) by the first kernel client instance which was created for the console, errors are printed to the console. Assuming this is a valid use of the API, how could this situation be handled without errors?

The sneaky question about `IKernel.IManager` is, what do you think about providing the managed `IKernel` instances? `IKernel.IManager.connectTo` will clone an existing kernel client, and therefore create a second websocket connection and so on. At least for the use with Comm, we see the need to just use an existing kernel client and connect a Comm.

**Comment by blink1073** [comment]
Hi @AlexTugarev, for the first question, I think the right answer here to is to also match against the local `clientId` using the message header before printing that error.

As for the second question, we have purposely kept them separate since each is a different "client".  Your options are to 1) Use the original kernel object itself or 2) Provide the `clientId` of the original kernel object.

In the context of JupyterLab, you can get the `kernel` of an existing notebook by creating a `widgetExtension` for notebook widgets, similar to what the [jupyterlab_widgets](https://github.com/ipython/ipywidgets/blob/master/jupyterlab_widgets/src/plugin.ts#L58) extension does.

**Comment by blink1073** [comment]
@AlexTugarev, instead I think it made more sense to just ignore the comm message if we are not handling it, cf #234.

**Comment by AlexTugarev** [comment]
Thanks for the hint at the `IWidgetExtension`. That looks very interesting, but unfortunately there is nothing similar for console widgets.

**Comment by blink1073** [comment]
Right, the console does not use the document machinery, because it is not backed by a file.  However, you could expose the console session as part of the plugin interface (PR welcome).

**Comment by blink1073** [comment]
Close this one then?

**Comment by AlexTugarev** [comment]
Sure. Thank you!
