### ISSUE TITLE
Shutting down a kernel or session by id should affect the running objects

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter-js-services#242]
Currently if a session is shut down by ID but there is still a client session it seems to cause a race condition on the server due the the kernel still trying to reconnect on a kernel id that ends up getting reused by the server.

We should not try to reconnect if the id has been explicitly shut down.

**Comment by blink1073** [comment]
@minrk, this was noticed when testing against both Notebook 4.2 and Notebook master.  We get the following activity:

```
[W 16:48:47.515 NotebookApp] Replacing stale connection: 89f57375-afd9-4ee0-b580-2b6fc2c1bded:a315322911dda7331652093533ae3c4b
[I 16:48:47.532 NotebookApp] Kernel started: 4a3bac25-5e09-43e5-8bb5-d7f93fc451c6
LOG: 'Starting WebSocket:', 'ws://localhost:8889/api/kernels/4a3bac25-5e09-43e5-8bb5-d7f93fc451c6'
```

But then a `kernelInfo()` request on the new kernel times out.

**Comment by blink1073** [comment]
https://github.com/jupyter/jupyterlab/pull/1069/commits/b5d401eb1e1535be7b6902288cf2f13cf8392220 is in the state that caused the error.  In one test, we shut down a session by id.  In another test, we attempt to `startNew` kernel and get its `kernelInfo`.

**Comment by minrk** [comment]
@blink1073 on it! #243 looks good to me for the client side, but I think we are probably doing something not quite right on the server side as well, so I'll dig in there.

**Comment by minrk** [comment]
@blink1073 I've run the tests in jupyter/jupyterlab@b5d401e a few times, but never see any errors or failures.

The 'Replacing stale connection' message is indicating that a websocket for a given kernel is reconnecting before the server has noticed that the previous connection was closed (close event could be pending in the tornado event queue). I see these messages sometimes, but not any errors or failures, and I wouldn't really expect them to cause errors.

It was the 'reuse' comment that made me think there's something going wrong in the server, but now I'm not sure there is. I can't see how the server would be re-using an ID, since each session or kernel gets a new UUID. I would expect new connections / reconnects to 404 on missing IDs once a session is closed.

**Comment by blink1073** [comment]
Oddly, it passed on Travis as well.  I guess we'll have to chalk this up to "doesn't work on my machine".
